### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by PharmCat** [AhmedSalih3d/SPHExample#2] opened 2023-11-06 13:01 UTC
Error when run MainSimulation, can't find update! nowhere

```
ERROR: UndefVarError: update! not defined
Stacktrace:
 [1] RunSimulation(; SaveLocation::String, SimulationName::String, NumberOfIterations::Int64, OutputIteration::Int64)
   @ Main c:\Users\vsarn\github\SPHExample\src\MainSimulation.jl:104
 [2] top-level scope
   @ c:\Users\xxx\github\SPHExample\src\MainSimulation.jl:168
```

**Comment by AhmedSalih3d** [comment] 2024-01-26 20:48
I have closed this since, I have not been able to reproduce. `update!` is part of CellListMap and on the latest main branch it seems to work fine. I suspect this might be due to Julia not being able to find / install the packages directly, when the error with using Pkg.add to add the code existed.

Thanks for making an issue! :)

**Closed by AhmedSalih3d** 2024-01-26 20:48 UTC
